### ISSUE TITLE
Nomos web UI Login button broken on Safari WebKit 

### ISSUE THREAD

**Issue by laftho** [vhs/nomos#272] opened 2019-01-13 03:56 UTC
Login button doesn't seem to do anything in Safari WebKit on MacOS Safari or iOS chrome or Safari.

**Comment by TyIsI** [comment] 2019-02-15 03:59
Duplicate of #226.

**Comment by TyIsI** [comment] 2019-02-15 04:55
As tested by multiple people, fixed in Safari 12.0.3

**Closed by TyIsI** 2019-02-15 04:55 UTC
