### ISSUE TITLE
Membership card not issuing

### ISSUE THREAD

**Issue by miststlkr** [vhs/nomos#198] opened 2016-07-11 18:23 UTC
I english gud.

The previous [object][object] message on successfully issuing a membership card no longer shows and the card serial does not get issued.

![image](https://cloud.githubusercontent.com/assets/1920178/16741802/cb2a7dd6-4759-11e6-80bd-b62d76881847.png)

**Comment by laftho** [comment] 2016-07-21 22:01
https://github.com/vhs/nomos/pull/202 fixes the popup message so it actually contains relevant details and/or error messages.

Generally speaking, if a card is already registered it can't be registered again. Also if you are issuing a card, unless there is an un-matched vhs_card_2015 payment for the associated email address it will fail to issue. This is probably the problem but I can't tell from this screenshot or details provided.

The issue is either resolved by informing the user properly via the improved messaging or this issue can be re-opened with a more useful error message.

**Closed** 2016-07-21 22:02 UTC
Labels: bug
